// Actual source/installed Painter against hanaworlds-contracts major 2 confirmed-placement/v1.
// FIXTURE boundary: the contract's public `confirmed-placement` fixture (per-cell and region cases,
// generated by the contracts package from its own public functions) run through the real Painter
// service: proposal.call -> contract request/context admission with fresh Host facts ->
// planGeometry/assembleBuild -> response coherence -> fresh Host facts again. Painter-local variants
// only re-bind digests through the public digestValue. No world, Canvas, Adapter, Brush, model or
// attachment is reached (the CreateBuildPlan cases use a scripted in-process llm port).
import test from 'node:test';
import assert from 'node:assert/strict';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
const root = process.env.PAINTER_TEST_PACKAGE ?? resolve(new URL('..', import.meta.url).pathname);
const { contracts: api, contractFixture } = await import(pathToFileURL(resolve(root, 'src/contract-package.mjs')));
const Painter = await import(pathToFileURL(resolve(root, 'src/index.mjs')));
const fx = contractFixture('confirmed-placement');
const main = contractFixture('main');
const OP = 'ValidateBuildProposal', REGION_OP = 'ValidateRegionProposal', PLAN_OP = 'CreateBuildPlan';
const clone = structuredClone;
const digest = (kind, value) => api.digestValue(kind, value).sha256;
const key = p => p.join(',');
const forbidden = () => new Proxy({}, { get(t, k) { if (typeof k === 'symbol') return Reflect.get(t, k); throw new Error('touched model/media'); } });
const CONTEXT = Object.keys(main.facts.sourceContext);
const named = new Map(api.confirmedPlacement.namedFailures.map(f => [f.failure, f]));
const accept = title => fx.perCell.accept.find(c => c.title.startsWith(title));

/** Host facts for a per-cell request: the retained source context and the current context are
 * the request's own context (what Workshop retained and still reads), unless `retained` differs. */
function hostFacts(request, { retained } = {}) {
  const facts = clone(main.facts);
  const context = Object.fromEntries(CONTEXT.map(k => [k, clone(request[k])]));
  facts.sourceContext = retained ? retained(clone(context)) : context;
  facts.currentContext = clone(context);
  Object.assign(facts.requestFacts, { sessionRef: request.sessionRef, currentTurnRevision: request.turnRevision,
    currentBriefDigest: request.referenceBriefDigest });
  return facts;
}
/** Painter with a counting Host facts port; `next(read)` may swap the facts the next read sees. */
function painterFor(facts, { next, llm = forbidden() } = {}) {
  const state = { reads: 0, facts };
  const localFacts = { async read() { state.reads++; const seen = clone(state.facts); if (next) next(state); return seen; } };
  return { state, painter: new Painter.ExteriorPainterV2({ localFacts, llm, attachments: forbidden() }) };
}
function refused(response, error) {
  assert.equal(response.result, null, JSON.stringify(response));
  assert.equal(response.error.code, error.code, JSON.stringify(response.error));
  assert.equal(response.error.reason, error.reason, JSON.stringify(response.error));
  assert.equal(response.error.mutationState, 'NONE');
  assert.equal(response.error.transactionRef, null);
}
const failure = name => { const f = named.get(name); return { code: f.code, reason: f.reason }; };
/** Re-bind every digest of a per-cell request after a Painter-local edit (public digestValue only). */
function rebind(r) {
  r.referenceBriefDigest = r.intent.referenceBriefDigest = digest('reference-brief', r.referenceBrief);
  r.targetFactsDigest = r.regionInspection.targetFactsDigest = digest('target-facts', r.targetFacts);
  r.intentDigest = digest('intent', r.intent);
  r.safetyProfile = clone(api.safetyProfileFromConfirmedIntent(r.intent));
  r.safetyProfileDigest = digest('safety-profile', r.safetyProfile);
  return r;
}
/** The world positions the released BUILD writes: its COVERAGE witness, which the contract checks
 * equals the exact final effect set. */
const written = build => build.witnesses.find(w => w.predicate === 'COVERAGE').facts.positions;

test('public accept cases: Painter returns exactly the published response; the effect set is the confirmed target', async () => {
  assert.equal(fx.perCell.accept.length, 4);
  for (const c of fx.perCell.accept) {
    for (const raw of [c.request, JSON.stringify(c.request)]) {
      const { painter, state } = painterFor(hostFacts(c.request));
      const response = await painter.call(OP, raw);
      assert.equal(response.error, null, `${c.title}: ${JSON.stringify(response.error)}`);
      // Complete equality with the contract's own response: build, operations, witnesses, digest.
      assert.deepEqual(response, c.response, c.title);
      api.validateBuildProposalResponse(c.request, response);
      assert.equal(state.reads, 2, `${c.title}: fresh Host facts before planning and before release`);
      const placement = c.request.intent.confirmedIntent.placement;
      const cells = written(response.result.build);
      if (placement === null) continue;
      if (placement.target.kind === 'EXACT_CELLS')
        assert.deepEqual(cells.map(key).sort(), placement.target.cells.map(key).sort(), `${c.title}: exact cells, all and only`);
      else {
        const { min, max } = placement.target.bounds;
        for (const p of cells) assert.ok(p.every((v, a) => v >= min[a] && v <= max[a]), `${c.title}: inside the confirmed extent`);
      }
      assert.doesNotThrow(() => api.requirePlacementTarget(placement, cells));
    }
  }
});

test('public reject cases: A->B, partial, outside extent, new view, stale, frame, missing/changed binding, old confirmation, known-empty', async () => {
  assert.equal(fx.perCell.reject.length, 10);
  for (const c of fx.perCell.reject) {
    const { painter } = painterFor(hostFacts(c.request));
    const response = await painter.call(OP, c.request);
    refused(response, c.error);
    if (c.error.placementFailure) assert.deepEqual(failure(c.error.placementFailure), { code: c.error.code, reason: c.error.reason }, c.title);
  }
});

test('confirmed extent is never silently re-sourced: a later or other inspection of the same World is refused by name', async () => {
  const base = accept('confirmed extent').request;
  for (const [view, name] of [['view1Later', 'PLACEMENT_REVISION_STALE'], ['view2', 'PLACEMENT_INSPECTION_CHANGED'],
    ['view1OtherFrame', 'PLACEMENT_FRAME_CHANGED']]) {
    const r = clone(base);
    r.regionInspection = clone(fx.inspections[view]); r.targetFacts = clone(fx.inspections[view].targetFacts);
    rebind(r);
    const { painter } = painterFor(hostFacts(r));
    refused(await painter.call(OP, r), failure(name));
  }
});

test('retained context continuity: Host retained a re-sampled inspection, or the world moved during planning, so nothing is released', async () => {
  const a = accept('confirmed A').request;
  // Workshop retained a new CURRENT_VIEW context after confirmation: request and retained facts differ.
  const resampled = painterFor(hostFacts(a, { retained: ctx => {
    ctx.regionInspection = clone(fx.inspections.view1Later); ctx.targetFacts = clone(fx.inspections.view1Later.targetFacts);
    ctx.targetFactsDigest = digest('target-facts', ctx.targetFacts); ctx.regionInspection.targetFactsDigest = ctx.targetFactsDigest;
    return ctx;
  } }));
  refused(await resampled.painter.call(OP, a), { code: 'TARGET_FACTS_STALE', reason: 'REVISION_CHANGED' });
  assert.equal(resampled.state.reads, 1, 'refused at the first fresh read, before planning');
  // The current context changes between the read before planning and the read before release.
  const moved = painterFor(hostFacts(a), { next: state => {
    state.facts.currentContext.regionInspection = clone(fx.inspections.view1Later);
  } });
  const response = await moved.painter.call(OP, a);
  refused(response, { code: 'TARGET_FACTS_STALE', reason: 'REVISION_CHANGED' });
  assert.equal(moved.state.reads, 2);
});

test('replay: same request returns the original after fresh facts; changed placement is REPLAY_MISMATCH; replay after a new view is refused', async () => {
  const c = accept('confirmed A');
  const f = painterFor(hostFacts(c.request));
  const first = await f.painter.call(OP, c.request);
  assert.deepEqual(first, c.response);
  assert.deepEqual(await f.painter.call(OP, JSON.stringify(c.request)), first);
  assert.equal(f.state.reads, 4);
  // A valid request on the same Session/context/requestId whose confirmed placement differs (extent).
  const changed = { ...clone(accept('confirmed extent').request), requestId: c.request.requestId };
  f.state.facts = hostFacts(changed);
  refused(await f.painter.call(OP, changed), { code: 'REPLAY_MISMATCH', reason: 'PAYLOAD_CHANGED' });
  f.state.facts = hostFacts(c.request);
  f.state.facts.currentContext.regionInspection = clone(fx.inspections.view1Later);
  refused(await f.painter.call(OP, c.request), { code: 'TARGET_FACTS_STALE', reason: 'REVISION_CHANGED' });
});

test('new proposal B with a new human confirmation is allowed; the old A confirmation on the B inspection is not', async () => {
  const b = accept('normal new proposal B');
  const { painter } = painterFor(hostFacts(b.request));
  assert.deepEqual(await painter.call(OP, b.request), b.response);
  // Same B request but the confirmed (and shown) placement is still A from view 1.
  const stale = clone(b.request);
  stale.intent.confirmedIntent.placement = clone(fx.placements.A);
  stale.referenceBrief.controls.placement = clone(fx.placements.A);
  rebind(stale);
  refused(await painterFor(hostFacts(stale)).painter.call(OP, stale), failure('PLACEMENT_INSPECTION_CHANGED'));
});

test('public region cases through painter-region/v3: exact/extent accepted unchanged; moved, outside or rebound refused', async () => {
  const hostRegion = r => ({ currentContext: clone(r.localContext), sessionRef: r.sessionRef, currentTurnRevision: r.turnRevision,
    currentBriefDigest: r.referenceBriefDigest, requestState: 'ACTIVE', replay: 'NEW', priorRequestDigest: null });
  for (const c of fx.region.accept) {
    const { painter } = painterFor(hostRegion(c.request));
    const response = await painter.call(REGION_OP, c.request);
    assert.equal(response.error, null, `${c.title}: ${JSON.stringify(response.error)}`);
    api.validateRegionProposalResponse(c.request, response);
    assert.deepEqual(response.result.build.block, c.request.proposal.block, c.title);
  }
  for (const c of fx.region.reject) refused(await painterFor(hostRegion(c.request)).painter.call(REGION_OP, c.request), c.error);
});

/** CreateBuildPlan on the same per-cell scenario: one bound image, no proposal; the scripted model
 * answers `boxes`. The confirmed placement binds the model path too (Painter, public functions). */
function planRequest(from) {
  const r = clone(from);
  delete r.proposal; delete r.localContext.regionInspection;
  r.referenceBrief.media = [{ attachmentRef: 'fixture-attachment-1', storedBytesDigest: 'a'.repeat(64),
    projectionVariantId: null, projectionBytesDigest: null, mediaType: 'image/png', bytes: 1024, width: 16, height: 16 }];
  return rebind(r);
}
/** Scripted in-process llm port (not a model): `answer` is a fixed proposal or a function of the
 * request facts the model actually received in its prompt text. */
function scriptedModel(answer) {
  const state = { calls: 0, received: [] };
  return { state, llm: {
    async resolveModelInfo() { return { inputModalities: ['text', 'image'] }; },
    async *stream({ messages }) {
      state.calls++;
      const text = messages[0].content.find(c => c.type === 'text').text;
      const facts = JSON.parse(text.slice(text.indexOf('\n') + 1));
      state.received.push(facts);
      const proposal = typeof answer === 'function' ? answer(facts) : answer;
      yield { type: 'text-delta', index: 0, text: JSON.stringify(proposal) }; yield { type: 'finish', reason: { kind: 'stop' } };
    },
  } };
}
async function plan(request, proposal) {
  const model = scriptedModel(proposal);
  const facts = { ...clone(main.facts.requestFacts), currentContext: clone(request.localContext),
    sessionRef: request.sessionRef, currentTurnRevision: request.turnRevision, currentBriefDigest: request.referenceBriefDigest };
  const painter = new Painter.ExteriorPainterV2({ localFacts: { async read() { return clone(facts); } },
    llm: model.llm, attachments: {} });
  return { response: await painter.call(PLAN_OP, request), model };
}

test('CreateBuildPlan: confirmed A planned as A; model boxes writing B, or a re-sampled inspection, are refused by name', async () => {
  const a = accept('confirmed A');
  const request = planRequest(a.request);
  const ok = await plan(request, a.request.proposal);
  assert.equal(ok.response.error, null, JSON.stringify(ok.response.error));
  assert.deepEqual(written(ok.response.result.build).map(key).sort(), fx.placements.A.target.cells.map(key).sort());
  const toB = fx.perCell.reject.find(x => x.title.includes('the boxes write B')).request.proposal;
  refused((await plan(request, toB)).response, failure('PLACEMENT_TARGET_MISMATCH'));
  const resampled = clone(request);
  resampled.regionInspection = clone(fx.inspections.view1Later); resampled.targetFacts = clone(fx.inspections.view1Later.targetFacts);
  rebind(resampled);
  const before = await plan(resampled, a.request.proposal);
  refused(before.response, failure('PLACEMENT_REVISION_STALE'));
  assert.equal(before.model.state.calls, 0, 'source binding is refused before any model call');
});

const localOf = (request, p) => p.map((v, i) => v - request.targetFacts.sampledBounds.min[i]);
const PROMPT_KEYS = ['request', 'confirmedIntent', 'purpose', 'styleText', 'region', 'offeredMaterials', 'imageCount', 'entrance', 'firstBuilding'];

test('CreateBuildPlan model input: the model receives exactly the confirmed target and plans A from it; without one the input is unchanged', async () => {
  // Exact A: the scripted model plans only from the cells it received (one 1x1x1 box per cell).
  const a = planRequest(accept('confirmed A').request);
  const fromPrompt = facts => ({ decision: 'BUILD', materials: { stone: { nodeName: 'fixture:stone', param2: 0 } },
    boxes: facts.confirmedPlacement.cells.map(c => ({ min: c, max: c, materialRef: 'stone' })) });
  const ok = await plan(a, fromPrompt);
  assert.equal(ok.model.state.calls, 1);
  const got = ok.model.state.received[0];
  assert.deepEqual(Object.keys(got), [...PROMPT_KEYS, 'confirmedPlacement']);
  assert.equal(got.confirmedPlacement.kind, 'EXACT_CELLS');
  assert.deepEqual(got.confirmedPlacement.cells, fx.placements.A.target.cells.map(p => localOf(a, p)));
  assert.equal(ok.response.error, null, JSON.stringify(ok.response.error));
  assert.deepEqual(written(ok.response.result.build).map(key).sort(), fx.placements.A.target.cells.map(key).sort());
  // A model that ignores the received target and writes B is refused, never re-based.
  const toB = fx.perCell.reject.find(x => x.title.includes('the boxes write B')).request.proposal;
  const ignored = await plan(a, toB);
  assert.deepEqual(ignored.model.state.received[0].confirmedPlacement, got.confirmedPlacement);
  refused(ignored.response, failure('PLACEMENT_TARGET_MISMATCH'));
  // Extent: the received bounds are the confirmed ones in the same local grid.
  const ext = accept('confirmed extent');
  const e = planRequest(ext.request);
  const inExtent = await plan(e, ext.request.proposal);
  const bounds = fx.placements.extentA.target.bounds;
  assert.deepEqual(inExtent.model.state.received[0].confirmedPlacement,
    { kind: 'ANCHORED_EXTENT', rule: inExtent.model.state.received[0].confirmedPlacement.rule,
      bounds: { min: localOf(e, bounds.min), max: localOf(e, bounds.max) } });
  assert.equal(inExtent.response.error, null, JSON.stringify(inExtent.response.error));
  // No structured placement: no confirmedPlacement key, the prompt facts keep the earlier key set.
  const none = accept('no structured placement');
  const n = await plan(planRequest(none.request), none.request.proposal);
  assert.deepEqual(Object.keys(n.model.state.received[0]), PROMPT_KEYS);
  assert.equal(n.response.error, null, JSON.stringify(n.response.error));
  assert.equal(Painter.promptText(planRequest(none.request)).includes('confirmedPlacement'), false);
  // Old source: refused before the model is called, so it never sees a stale target.
  const stale = clone(a);
  stale.regionInspection = clone(fx.inspections.view1Later); stale.targetFacts = clone(fx.inspections.view1Later.targetFacts);
  rebind(stale);
  const before = await plan(stale, fromPrompt);
  refused(before.response, failure('PLACEMENT_REVISION_STALE'));
  assert.equal(before.model.state.calls, 0);
});
